* Stuff i use
+ *Distro*: [[https://guix.gnu.org/][GuixSD]]
+ *WM*: [[https://xmonad.org/][XMonad]]
+ *Editor (and therapist)*: [[https://github.com/hlissner/doom-emacs][doom emacs]] on [[http://akrl.sdf.org/gccemacs.html][Emacs Native Comp]]
+ *Scripting*: [[https://www.gnu.org/software/guile/][GNU Guile]]
+ *Keyboard*: [[https://ergodox-ez.com/][Ergodox EZ (stick with the EZ unless you do a custom dactyl folks)]]
+ *Utilities*: 
  + XDG-Utils replacement: [[https://github.com/chmln/handlr][handlr]] (I have a package definition for guix, but i haven't had time to make a PR/Patch yet, send a mail if you need it)

* +Propaganda+ Recommended reading
Start with Paul,
+ [[http://www.paulgraham.com/hp.html][Paul Graham: Hackers and painters]]
#+begin_quote
When I say that the answer is for hackers to have day jobs, and work on beautiful software on the side, I'm not proposing this as a new idea. This is what open-source hacking is all about. What I'm saying is that open-source is probably the right model, because it has been independently confirmed by all the other makers.
#+end_quote
#+begin_quote
Great software, likewise, requires a fanatical devotion to beauty. If you look inside good software, you find that parts no one is ever supposed to see are beautiful too.
#+end_quote
#+begin_quote
I think this is the right model for collaboration in software too. Don't push it too far. When a piece of code is being hacked by three or four different people, no one of whom really owns it, it will end up being like a common-room. It will tend to feel bleak and abandoned, and accumulate cruft. The right way to collaborate, I think, is to divide projects into sharply defined modules, each with a definite owner, and with interfaces between them that are as carefully designed and, if possible, as articulated as programming languages.
#+end_quote
#+begin_quote
What you learn about programming in college is much like what you learn about books or clothes or dating: what bad taste you had in high school.
#+end_quote
+ [[http://www.paulgraham.com/lies.html][Paul Graham: Lies we tell kids]]
+ [[http://www.paulgraham.com/think.html][Paul Graham: How to think]]
+ [[https://fsf.org][Free Software Foundation: Homepage]]
+ [[https://stallman.org/][Richard M. Stallman: Homepage]]
+ [[https://suckless.org/philosophy/][Suckless: Philosophy]]
+ [[http://harmful.cat-v.org/][cat-v: Harmfull stuff]]
+ [[https://ambrevar.xyz/guix-advance/][Ambrevar: Guix]]

*** Eric S. Raymond
WARNING/DISCLAIMER: Eric has a blunt personality, i don't nescesarrily care for the most of his "hottakes".
Therefore one might need some helf finding the "nuggets of gold" with Raymond. I present a sample here.
+ [[http://www.catb.org/~esr/faqs/smart-questions.html][How to ask questions]]
+ [[http://www.catb.org/jargon/][Jargon file]]
+ [[https://tldp.org/HOWTO/Unix-and-Internet-Fundamentals-HOWTO/][Unix and Internet Fundamentals]]
